Vulnerability scan

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -24,17 +24,19 @@ steps:
   - name: 'ssh'
     path: /root/.ssh
 
+#Static code analysis
 - name: 'gcr.io/cloud-builders/mvn'
   args: ['install']
 - name: "gcr.io/$PROJECT_ID/sonar-scanner:latest" 
   args: [ 
-    "-Dsonar.projectKey=hello-world", 
+    "-Dsonar.projectKey=cloufunction", 
     "-Dsonar.sources=./src", 
-    "-Dsonar.host.url=http://35.200.250.32:9000", 
+    "-Dsonar.host.url=http://35.244.55.55:9000/",
     "-Dsonar.login=${_SONAR_TOKEN}",
     "-Dsonar.java.binaries=.",
     "-Dsonar.qualitygate.wait=true" ]
 
+#Deploying google cloud function
 - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
   args:
   - gcloud
@@ -51,7 +53,54 @@ steps:
 # Build the image
 - name: 'gcr.io/cloud-builders/docker'
   args: ['build', '-t', 'gcr.io/niveustraining/my-image:v1.0', '.']
-    
+
+# Check the vulnerabilities and exit if it meets severity level
+- id: scan
+  name: gcr.io/cloud-builders/gcloud
+  entrypoint: /bin/bash
+  args:
+   - -c
+   - |
+     gcloud artifacts docker images scan 'gcr.io/niveustraining/my-image:v1.0' \
+     --format='value(response.scan)' > /workspace/docdags/scan_id.txt
+       
+- id: severity check2
+  name: gcr.io/cloud-builders/gcloud
+  entrypoint: /bin/bash
+  args:
+    - -c
+    - | 
+      gcloud artifacts docker images list-vulnerabilities \
+      $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
+      | if grep -Fxq $_SEVERITY2 
+        then echo 'Failed vulnerability check - CRITICAL'
+        exit 1 
+        fi
+          
+- id: severity check1
+  name: gcr.io/cloud-builders/gcloud
+  entrypoint: /bin/bash
+  args:
+    - -c
+    - | 
+      gcloud artifacts docker images list-vulnerabilities \
+      $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
+        | if grep -Fxq $_SEVERITY1
+          then echo 'Failed vulnerability check - HIGH'
+          exit 1 
+          fi
+# - id: severity check
+#   name: gcr.io/cloud-builders/gcloud
+#   entrypoint: /bin/bash
+#   args:
+#     - -c
+#     - | 
+#       gcloud artifacts docker images list-vulnerabilities \
+#       $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
+#         | if grep -Fxq $_SEVERITY 
+#           then echo 'Failed vulnerability check - MEDIUM'
+#           exit 1 
+#           fi
 # Push the image to GCR
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/niveustraining/my-image:v1.0']
@@ -67,4 +116,7 @@ availableSecrets:
     env: 'SSH_KEY'
 
 substitutions:
-  _SONAR_TOKEN: "sqp_2e4f108a58ca9cc2ee09235b72efcf3f44b58f54"
+  _SONAR_TOKEN: "sqp_7d537752d8e9be22eb8b221cd03bb68cff0b6e9a"
+  # _SEVERITY: MEDIUM
+  _SEVERITY1: HIGH
+  _SEVERITY2: CRITICAL
