Update cloudbuild.yaml

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -55,40 +55,40 @@ steps:
   args: ['build', '-t', 'gcr.io/niveustraining/my-image:v1.0', '.']
 
 # Check the vulnerabilities and exit if it meets severity level
-- id: scan
-  name: gcr.io/cloud-builders/gcloud
-  entrypoint: /bin/bash
-  args:
-   - -c
-   - |
-     gcloud artifacts docker images scan 'gcr.io/niveustraining/my-image:v1.0' \
-     --format='value(response.scan)' > /workspace/docdags/scan_id.txt
+# - id: scan
+#   name: gcr.io/cloud-builders/gcloud
+#   entrypoint: /bin/bash
+#   args:
+#    - -c
+#    - |
+#      gcloud artifacts docker images scan 'gcr.io/niveustraining/my-image:v1.0' \
+#      --format='value(response.scan)' > /workspace/docdags/scan_id.txt
        
-- id: severity check2
-  name: gcr.io/cloud-builders/gcloud
-  entrypoint: /bin/bash
-  args:
-    - -c
-    - | 
-      gcloud artifacts docker images list-vulnerabilities \
-      $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
-      | if grep -Fxq $_SEVERITY2 
-        then echo 'Failed vulnerability check - CRITICAL'
-        exit 1 
-        fi
+# - id: severity check2
+#   name: gcr.io/cloud-builders/gcloud
+#   entrypoint: /bin/bash
+#   args:
+#     - -c
+#     - | 
+#       gcloud artifacts docker images list-vulnerabilities \
+#       $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
+#       | if grep -Fxq $_SEVERITY2 
+#         then echo 'Failed vulnerability check - CRITICAL'
+#         exit 1 
+#         fi
           
-- id: severity check1
-  name: gcr.io/cloud-builders/gcloud
-  entrypoint: /bin/bash
-  args:
-    - -c
-    - | 
-      gcloud artifacts docker images list-vulnerabilities \
-      $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
-        | if grep -Fxq $_SEVERITY1
-          then echo 'Failed vulnerability check - HIGH'
-          exit 1 
-          fi
+# - id: severity check1
+#   name: gcr.io/cloud-builders/gcloud
+#   entrypoint: /bin/bash
+#   args:
+#     - -c
+#     - | 
+#       gcloud artifacts docker images list-vulnerabilities \
+#       $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
+#         | if grep -Fxq $_SEVERITY1
+#           then echo 'Failed vulnerability check - HIGH'
+#           exit 1 
+#           fi
 # - id: severity check
 #   name: gcr.io/cloud-builders/gcloud
 #   entrypoint: /bin/bash
@@ -118,5 +118,5 @@ availableSecrets:
 substitutions:
   _SONAR_TOKEN: "sqp_7d537752d8e9be22eb8b221cd03bb68cff0b6e9a"
   # _SEVERITY: MEDIUM
-  _SEVERITY1: HIGH
-  _SEVERITY2: CRITICAL
+#   _SEVERITY1: HIGH
+#   _SEVERITY2: CRITICAL
