Initial Commit

diff --git a/cloudbuild.yaml b/cloudbuild.yaml
--- a/cloudbuild.yaml
+++ b/cloudbuild.yaml
@@ -89,18 +89,18 @@ steps:
           then echo 'Failed vulnerability check - HIGH'
           exit 1 
           fi
-# - id: severity check
-#   name: gcr.io/cloud-builders/gcloud
-#   entrypoint: /bin/bash
-#   args:
-#     - -c
-#     - | 
-#       gcloud artifacts docker images list-vulnerabilities \
-#       $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
-#         | if grep -Fxq $_SEVERITY 
-#           then echo 'Failed vulnerability check - MEDIUM'
-#           exit 1 
-#           fi
+- id: severity check
+  name: gcr.io/cloud-builders/gcloud
+  entrypoint: /bin/bash
+  args:
+    - -c
+    - | 
+      gcloud artifacts docker images list-vulnerabilities \
+      $(cat /workspace/docdags/scan_id.txt) --format='value(vulnerability.effectiveSeverity)' \
+        | if grep -Fxq $_SEVERITY 
+          then echo 'Failed vulnerability check - MEDIUM'
+          exit 1 
+          fi
 # Push the image to GCR
 - name: 'gcr.io/cloud-builders/docker'
   args: ['push', 'gcr.io/niveustraining/my-image:v1.0']
@@ -117,6 +117,6 @@ availableSecrets:
 
 substitutions:
   _SONAR_TOKEN: "sqp_7d537752d8e9be22eb8b221cd03bb68cff0b6e9a"
-  # _SEVERITY: MEDIUM
+  _SEVERITY: MEDIUM
   _SEVERITY1: HIGH
   _SEVERITY2: CRITICAL
